#pragma once

namespace Problem2
{
	// Problem 2: Even Fibonacci numbers
	// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	// By starting with 1 and 2, the first 10 terms will be:
	// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	int run()
	{
		int sum= 0;
		int term1 = 1;
		int term2 = 2;
		int nextTerm = 0;


		while (term1 <= 4000000)
		{
			if (term1 % 2 == 0)
			{
				sum += term1;
			}

			nextTerm = term1 + term2;
			term1 = term2;
			term2 = nextTerm;
		}

		return sum;
	}
}